### ISSUE TITLE
Date Picker shows wrong weekdays

### ISSUE THREAD

**Issue by w-andre** [DevExpress/DevExtreme-Intl#11]
I tried to setup DevExtreme with DevExtreme-Intl and noticed a problem with the date picker of the date box component.
In the screenshot you can see the selected date is a Tuesday but the date picker shows it as a Wednesday:

![image](https://cloud.githubusercontent.com/assets/12671470/21349009/0e3ceffc-c6b0-11e6-9dca-ec5c01380c3f.png)
`$("#datebox-dxcustom").dxDateBox({
    displayFormat: "longDate",
    value: new Date()
});`

Working example: [Plunker](https://plnkr.co/edit/xrlKEy62YHaKK4BXUTwb?p=preview)

**Comment by nightskylark** [comment]
Hi,
It looks like the issue reproduction depends on the browser language. Can you please evaluate `navigator.language` in the browser console and tell us what it returns?

**Comment by w-andre** [comment]
`navigator.language` evalutes to `"en-US"` on my machine.
The locale of my operating system is set to "de-DE".

I tried to change the language in my browser (Chrome 55, Windows 10) to match my operating system configuration. `navigator.language` then evaluates to `"de"` but the date picker stays exactly the same.
