### ISSUE TITLE
Uncaught TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by MojoDK** [DevExpress/DevExtreme-Intl#12]
Hi

I put this line in my HTML...

> <script src="https://unpkg.com/devextreme-intl/dist/devextreme-intl.min.js"></script>

... and I get this error:

> Uncaught TypeError: Cannot read property 'config' of undefined
>     at devextreme-intl.min.js:2
>     at devextreme-intl.min.js:2
> (anonymous) @ devextreme-intl.min.js:2
> (anonymous) @ devextreme-intl.min.js:2

I can't find any documentation here on "config".

Any idea?

**Comment by nightskylark** [comment]
Hi
It looks like the DevExtreme script is not added into your app or added incorrectly. Take note that the `devextreme-intl` script should be inserted behind the `devextreme` script tag.

**Comment by MojoDK** [comment]
My bad ... my bad english (I'm Danish) thought "behind" was the same as "before" ... I thought one would use the word "after" ... but I'm still learning the language :) Thanks anyway.
