### ISSUE TITLE
Change date separator?

### ISSUE THREAD

**Issue by MojoDK** [DevExpress/DevExtreme-Intl#14]
Hi

Danish dates look like this ... dd-mm-yyyy ... how can I change it in DevExtreme-Intl? It shows as dd/mm/yyyy.

I've tried with both...
DevExpress.localization.locale(navigator.language);
DevExpress.localization.locale("da-DK");

... still shows dd/mm/yyyy.

Thanks

**Comment by nightskylark** [comment]
The ECMAScript Internationalization API allows formatting dates only by the locale data. As I know, browsers use CLDR data for its implementation. But the short date pattern in CLDR data contains slashes, not dashes.
https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/da/ca-gregorian.json#L314
If you need to customize the date formatting using the Intl approach, it's better to use a [format object](https://js.devexpress.com/Documentation/16_2/ApiReference/Common/Object_Structures/format/) with custom `formatter` and `parser` methods.
