### ISSUE TITLE
Wrong hours in some time zones (Chrome, FireFox)

### ISSUE THREAD

**Issue by nightskylark** [DevExpress/DevExtreme-Intl#22]
Wait until bugs in Chrome and FireFox Intl implementations will be fixed:
https://bugs.chromium.org/p/chromium/issues/detail?id=680114
https://bugzilla.mozilla.org/show_bug.cgi?id=1330307

**Comment by DokaRus** [comment]
FireFox has fixed the issue and the problem isn't reproduced.
The Chromium ticket is still active. The comment of January 2017 allows us to conclude that the problem, as well as in FireFox, depended on the operating system:

>Able to reproduce this issue on windows 10,Mac 10.12.2<...>Unable to reproduce this issue on Unbuntu 14.04

At the moment, the issue isn't reproduced on win10(v. 1809), Mac 10.14.5 using Chrome stable(v. 75).
