### ISSUE TITLE
Translate months and weekdays for date box in Angular CLI application

### ISSUE THREAD

**Issue by fgNv** [DevExpress/DevExtreme-Intl#32]
Hello, is there anyway to translate months and weekdays that are displayed in the date box in an Angular CLI application? 

I've tried to use Globalize but couldn't make it work.

**Comment by NickMitrokhin** [comment]
Hello,

Please take a look at the [dxDataGrid does not apply an LDML format for dates if Intl is used](https://www.devexpress.com/Support/Center/Question/Details/T560453) ticket where we discussed how to add Globalize to an app created using the Angular CLI. If this does not help, please submit a ticket regarding your issue in our [Support Center](https://www.devexpress.com/support/center). We will do our best to help you.
