### ISSUE TITLE
Add possibility to override deadult language options

### ISSUE THREAD

**Issue by Franki1986** [DevExpress/DevExtreme-Intl#56]
In german, per default the date and time is displayed with leading zeros.
I know this is a default that comes from Intl. But you could give a possibility to override this options.
Since the defaults are loaded here:

```
	Object.defineProperty(intlFormats, 'shortdateshorttime', {
	    get: function() {
	        var defaultOptions = Intl.DateTimeFormat(locale()).resolvedOptions();
                /*
                var customOptions = getCustomOptions(locale());
                defaultOptions =  customOptions  != null ? customOptions : defaultOptions; 
                */
	        return { year: defaultOptions.year, month: defaultOptions.month, day: defaultOptions.day, hour: 'numeric', minute: 'numeric' };
	    }
	});
```

There could be a global function that initializes custom options for a specific language.

**Comment by nightskylark** [comment]
Hi
It's better to use custom formats instead of modifying default ones. If you need help with some specific scenario, please contact us in our [Support Center](https://www.devexpress.com/Support/Center/).
