### ISSUE TITLE
Change locale on the fly

### ISSUE THREAD

**Issue by duongphuhiep** [DevExpress/DevExtreme-Intl#88]
Hello,

it appears that the support team didn't see all the complains in this old issue

https://github.com/DevExpress/DevExtreme-Intl/issues/49

So I'm opening it again, hoping we will have a clear answer from the support team.

There is not a button to Re-open a closed issue so I created a new one. Please feel free

* to re-open the issues #49 and close this duplicated one.
* Or close both of them with a clear answer about the question "will it be fixed, or it will be a know issue forever?"

Thank you

**Comment by LexDX** [comment]
Hi,

We remember the initial issue. We will address it once we have any news.
